# Dependencies
# Permalinks


# Setup
title:            'Teaching Portfolio'
tagline:          'My teaching philosophy'
description:      'Herman Kamper'
# url:              https://www.kamperh.com/teaching_portfolio
url:              http://localhost:4000
baseurl:          ''
paginate:         5
permalink:        pretty

# Details
author:
  name:           'Herman Kamper'
  url:            https://www.kamperh.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# markdown:         redcarpet
# highlighter:      pygments
# relative_permalinks: true
# tagline:          'A Jekyll theme'
# version:          2.1.0
# github:
#   repo:           https://github.com/poole/hyde
